version: '2'
services:
  nginx:
    build: .
    depends_on:
     - redmine
     - owncloud
    links:
     - redmine:remine
     - owncloud:owncloud
    ports:
     - "80:80"

  redmine:
    image: redmine 
    links:
      - db:db
    volumes:
      - .:/usr/src/redmine/files
        
  owncloud:
    image: owncloud
    links:
      - db:db
    volumes:
      - .:/var/www/html
  db:
    image: orchardup/mysql
    environment:
      -	MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE: openup
      
